export const USER_SIGNIN = 'USER_SIGNIN' // 登陆
export const USER_SIGNOUT = 'USER_SIGNOUT' // 退出
export const USER_INFO = 'USER_INFO'  // 用户信息
export const MSG_COUNT = 'MSG_COUNT'  // 消息数量
export const PREV_URL_NAME = 'PREV_URL_NAME'  // 记录上一次链接名称
export const CLEAR_PREV_URL_NAME = 'CLEAR_PREV_URL_NAME'  // 清空上一次链接
export const HIDE_HEADER = 'HIDE_HEADER'  // 是否隐藏头部
export const PLATFORM = 'PLATFORM'  // 来源是PC or H5
export const GLOBAL_SEARCH_LIBRARY_OF_GOODS = 'GLOBAL_SEARCH_LIBRARY_OF_GOODS' // 全局搜索商品
export const GLOBAL_SEARCH_LIBRARY_OF_GOODS_CLEAR = 'GLOBAL_SEARCH_LIBRARY_OF_GOODS_CLEAR' // 全局搜索商品清空
export const THE_SHOPPING_CART_LENGTH_THEBACKGROUND = 'THE_SHOPPING_CART_LENGTH_THEBACKGROUND' // 购物车数量
export const THE_SHOPPING_CART_LENGTH_THEBACKGROUND_CLEAR = 'THE_SHOPPING_CART_LENGTH_THEBACKGROUND_CLEAR' // 清空购物车
export const THE_ORDER_SHOPPING_CART_IDS_GLOBAL = 'THE_ORDER_SHOPPING_CART_IDS_GLOBAL' // 添加订单id
export const THE_ORDER_SHOPPING_CART_IDS_GLOBAL_CLEAR = 'THE_ORDER_SHOPPING_CART_IDS_GLOBAL_CLEAR'  // 清空订单id
export const THE_ORDER_SHOPPING_NUMBER = 'THE_ORDER_SHOPPING_NUMBER' // 记录进货单数量
export const THE_ORDER_SHOPPING_NUMBER_CLEAR = 'THE_ORDER_SHOPPING_NUMBER_CLEAR' // 清空进货单数量

